FROM node:20-alpine

WORKDIR /app

# pnpm 11 requires Node 22+ and uses node:sqlite. Keep Docker on Node 20 with pnpm 10.
RUN corepack enable && corepack prepare pnpm@10.25.0 --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --no-frozen-lockfile

COPY . .

# Build reads public VITE_* variables from hosting build args/env so Vite can
# inject them into bundled JS. Runtime-only secrets stay in the host env.
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_PAYSTACK_PUBLIC_KEY
ARG VITE_HCAPTCHA_SITEKEY
ARG VITE_API_BASE_URL
ARG VITE_APP_URL
ARG VITE_PAYPAL_CLIENT_ID
ARG VITE_VAPID_PUBLIC_KEY
ARG VITE_ENABLE_WEB_PUSH
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY
ARG NEXT_PUBLIC_HCAPTCHA_SITEKEY
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY \
    VITE_PAYSTACK_PUBLIC_KEY=$VITE_PAYSTACK_PUBLIC_KEY \
    VITE_HCAPTCHA_SITEKEY=$VITE_HCAPTCHA_SITEKEY \
    VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_APP_URL=$VITE_APP_URL \
    VITE_PAYPAL_CLIENT_ID=$VITE_PAYPAL_CLIENT_ID \
    VITE_VAPID_PUBLIC_KEY=$VITE_VAPID_PUBLIC_KEY \
    VITE_ENABLE_WEB_PUSH=$VITE_ENABLE_WEB_PUSH \
    NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
    NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
    NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=$NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY \
    NEXT_PUBLIC_HCAPTCHA_SITEKEY=$NEXT_PUBLIC_HCAPTCHA_SITEKEY
RUN pnpm run build

EXPOSE 8081

# Runtime: environment variables are loaded from Render, Oracle/OCI, or another host.
CMD ["sh", "-c", "pnpm start"]
