import type express from "express";
import Stripe from "stripe";
import { supabaseAdmin } from "../supabase-admin";
import { paypalApi } from "../services/paypal-api";
import { getActiveVapidPublicKey, sendPushToUser } from "../push-server/pushServer";
import { ServerActor } from "../auth";
import { enqueuePolicyScan, runDailyModerationScan } from "../moderation/moderationWorker";
import { publishRealtime } from "../realtime/realtimeHub";
import { enqueueJob, queueStats } from "../jobs/queue";
import { parsePagination, responseCacheMiddleware, selectFields, clearApiCache } from "../performance/cache";
import { requireErpPermission } from "../security/permissions";

const sanitizeText = (value: unknown, max = 160) => String(value || "").trim().slice(0, max);
const normalizeCurrencyCode = (currency: unknown) => { const normalized = String(currency || "USD").trim().toUpperCase(); if (normalized === "KSH" || normalized === "KES") return "KES"; if (normalized === "$") return "USD"; return normalized; };
const money = (value: unknown) => Math.max(0.01, Number(Number(value || 0).toFixed(2)));
const getPaypalClientId = () => process.env.PAYPAL_CLIENT_ID || process.env.VITE_PAYPAL_CLIENT_ID || "";
const getPaypalSecret = () => process.env.PAYPAL_CLIENT_SECRET || process.env.PAYPAL_SECRET_KEY || "";
const PAYPAL_SUPPORTED_CURRENCIES = new Set(["AUD", "BRL", "CAD", "CNY", "CZK", "DKK", "EUR", "HKD", "HUF", "ILS", "JPY", "MYR", "MXN", "TWD", "NZD", "NOK", "PHP", "PLN", "GBP", "RUB", "SGD", "SEK", "CHF", "THB", "USD"]);
const paypalCurrency = (currency: unknown, fallback = "USD") => { const normalized = normalizeCurrencyCode(currency); return PAYPAL_SUPPORTED_CURRENCIES.has(normalized) ? normalized : fallback; };
const paypalFxRate = (from: string, to: string) => { if (from === to) return 1; const envKey = `PAYPAL_FX_${from}_TO_${to}`; const envRate = Number(process.env[envKey]); if (envRate > 0) return envRate; if (from === "KES" && to === "USD") return Number(process.env.PAYPAL_KES_TO_USD_RATE || 0.0078); return 1; };
const paypalSettlementAmount = (amount: number, fromCurrency: string, toCurrency: string) => money(amount * paypalFxRate(fromCurrency, toCurrency));

export type RouteDeps = { requireActor: (req: express.Request) => Promise<ServerActor>; requireAdmin: (req: express.Request) => Promise<ServerActor>; rateLimit: (name: string, max?: number, windowMs?: number) => express.RequestHandler; insertNotificationSafe: (notification: any) => Promise<any>; sendInvoiceEmail: (to: string, subject: string, body: string) => Promise<any>; stripe: Stripe | null; };

async function createRealtimeNotification(deps: RouteDeps, input: { actorId: string; userId: string; title: string; body: string; type: string; deepLink: string; idempotencyKey?: string }) { const key = input.idempotencyKey || `${input.actorId}:${input.userId}:${input.type}:${input.title}:${input.body}:${input.deepLink}`.slice(0, 500); const data = await deps.insertNotificationSafe({ user_id: input.userId, title: input.title, body: input.body, type: input.type, deep_link: input.deepLink, idempotency_key: key }); publishRealtime({ type: "notification", userId: input.userId, payload: { id: data?.id, title: input.title, body: input.body, notificationType: input.type, link: input.deepLink } }); enqueueJob("push-notification", () => sendPushToUser(input.userId, { type: input.type as any, title: input.title, body: input.body, url: input.deepLink || "/", icon: "/struta_light_mode.png", badge: "/struta_light_mode.png" })); return data; }
async function syncPaidRequest(requestId: string | null | undefined, amount: number, currency: string) { if (!requestId) return; const { data: request } = await supabaseAdmin.from("service_requests").select("id,notes,status").eq("id", requestId).maybeSingle(); if (!request) return; let parsed: any = {}; try { parsed = request.notes ? JSON.parse(request.notes) : {}; } catch { parsed = { custom_notes: request.notes }; } const notes = JSON.stringify({ ...parsed, payment_requested: true, payment_amount: amount, payment_currency: currency, payment_status: "paid", status: "paid" }); await supabaseAdmin.from("service_requests").update({ notes, status: request.status === "completed" ? request.status : "accepted", updated_at: new Date().toISOString() }).eq("id", request.id); }
async function recordInvoiceLedger(_params: any) { return null; }

export function registerProductionRoutes(app: express.Express, deps: RouteDeps) {
  app.get("/api/vapid-public-key", (_req, res) => res.json({ publicKey: getActiveVapidPublicKey() }));
  app.get("/api/push/vapid-public-key", (_req, res) => res.json({ publicKey: getActiveVapidPublicKey() }));

  app.post("/api/request/delete", deps.rateLimit("request-delete", 30), async (req, res) => {
    try {
      const actor = await deps.requireActor(req);
      const requestId = sanitizeText(req.body?.requestId || req.body?.id, 120);
      if (!requestId) return res.status(400).json({ error: "Missing requestId." });
      const { data: request, error: readError } = await supabaseAdmin.from("service_requests").select("id,requester_id,requester_email,provider_id").eq("id", requestId).maybeSingle();
      if (readError) throw readError;
      if (!request) return res.status(404).json({ error: "Request not found." });
      const allowed = actor.role === "admin" || request.requester_id === actor.id || request.provider_id === actor.id || String(request.requester_email || "").toLowerCase() === String(actor.email || "").toLowerCase();
      if (!allowed) return res.status(403).json({ error: "You do not have permission to delete this request." });
      await supabaseAdmin.from("invoices").delete().eq("request_id", requestId);
      await supabaseAdmin.from("payments").delete().eq("request_id", requestId);
      await supabaseAdmin.from("service_requests").delete().eq("id", requestId);
      clearApiCache();
      publishRealtime({ type: "request_deleted", userId: actor.id, payload: { requestId } });
      res.json({ ok: true });
    } catch (error: any) { res.status(error.message?.includes("Authentication") ? 401 : 500).json({ error: error.message || "Could not delete request." }); }
  });

  app.post("/api/notifications/create", deps.rateLimit("notifications-create", 120), async (req, res) => { try { const actor = await deps.requireActor(req); const targetUserId = sanitizeText(req.body?.userId, 80); const title = sanitizeText(req.body?.title, 160); const body = sanitizeText(req.body?.message || req.body?.body, 500); const type = sanitizeText(req.body?.type || "general", 40); const deepLink = sanitizeText(req.body?.link || req.body?.deep_link || "", 240); const idempotencyKey = sanitizeText(req.body?.idempotencyKey || req.body?.idempotency_key, 500); if (!targetUserId || !title || !body) return res.status(400).json({ error: "Missing userId, title, or message." }); const data = await createRealtimeNotification(deps, { actorId: actor.id, userId: targetUserId, title, body, type, deepLink, idempotencyKey }); res.json({ ok: true, id: data?.id }); } catch (error: any) { console.error("[notifications/create]", error); res.status(error.message?.includes("Authentication") ? 401 : 500).json({ error: error.message || "Could not create notification." }); } });
  app.post("/api/moderation/scan", deps.rateLimit("moderation-scan", 30), async (req, res) => { try { const actor = await deps.requireActor(req); const userId = sanitizeText(req.body?.userId || actor.id, 80); const content = sanitizeText(req.body?.content, 5000); const sourceType = sanitizeText(req.body?.sourceType || "chat", 30) as any; const sourceId = sanitizeText(req.body?.sourceId, 120); if (userId !== actor.id && actor.role !== "admin") return res.status(403).json({ error: "Permission denied." }); if (!content) return res.status(400).json({ error: "Content is required." }); const result = await enqueuePolicyScan({ userId, sourceType, sourceId, content, metadata: { scannedBy: actor.id } }); publishRealtime({ type: "policy_review", userId, payload: result }); res.json({ ok: true, ...result }); } catch (error: any) { res.status(500).json({ error: error.message || "Moderation scan failed." }); } });
  app.post("/api/admin/moderation/daily-scan", deps.rateLimit("daily-moderation", 5), async (req, res) => { try { await deps.requireAdmin(req); const jobId = enqueueJob("daily-moderation-scan", runDailyModerationScan, 1); res.json({ ok: true, jobId, queue: queueStats() }); } catch (error: any) { res.status(error.message?.includes("Admin") ? 403 : 500).json({ error: error.message || "Could not start moderation scan." }); } });
  app.get("/api/admin/policy-queue", deps.rateLimit("policy-queue", 60), responseCacheMiddleware(10_000), async (req, res) => { try { await deps.requireAdmin(req); const { from, to, page, limit } = parsePagination(req, { limit: 50, max: 200 }); const { data, error, count } = await supabaseAdmin.from("policy_review_queue").select("id,user_id,source_type,source_id,severity,action,reason,status,created_at,metadata", { count: "exact" }).order("created_at", { ascending: false }).range(from, to); if (error) throw error; res.json({ items: data || [], page, limit, total: count || 0 }); } catch (error: any) { res.status(error.message?.includes("Admin") ? 403 : 500).json({ error: error.message || "Could not load policy queue." }); } });

  app.get("/api/cases", deps.rateLimit("cases-list", 120), responseCacheMiddleware(8_000), async (req, res) => { try { const actor = await deps.requireActor(req); const { from, to, page, limit } = parsePagination(req, { limit: 50, max: 150 }); const fields = selectFields(req, ["id", "requester_id", "provider_id", "provider_type", "request_title", "request_details", "status", "notes", "created_at", "updated_at"], "id,requester_id,provider_id,provider_type,request_title,status,created_at,updated_at"); const { data, error, count } = await supabaseAdmin.from("service_requests").select(fields, { count: "exact" }).or(`requester_id.eq.${actor.id},provider_id.eq.${actor.id}`).order("created_at", { ascending: false }).range(from, to); if (error) throw error; res.json({ cases: data || [], page, limit, total: count || 0 }); } catch (error: any) { res.status(error.message?.includes("Authentication") ? 401 : 500).json({ error: error.message || "Could not load cases." }); } });
  app.get("/api/erp/cases", deps.rateLimit("erp-cases", 80), responseCacheMiddleware(8_000), async (req, res) => { try { const actor = await deps.requireActor(req); requireErpPermission(actor, "view_assigned_cases"); const { from, to, page, limit } = parsePagination(req, { limit: 50, max: 150 }); const base = supabaseAdmin.from("erp_cases").select("id,organization_id,title,status,assigned_to,created_at,updated_at", { count: "exact" }).order("updated_at", { ascending: false }).range(from, to); const query = actor.staff_role === "coordinator" || actor.staff_role === "admin" || actor.role === "admin" ? base.eq("organization_id", actor.organization_id || actor.id) : base.contains("assigned_to", [actor.id]); const { data, error, count } = await query; if (error) throw error; res.json({ cases: data || [], page, limit, total: count || 0 }); } catch (error: any) { res.status(error.message?.includes("permission") ? 403 : 500).json({ error: error.message || "Could not load ERP cases." }); } });

  app.get("/api/payments/provider-profile/:providerId", deps.rateLimit("provider-profile-public-read", 80), responseCacheMiddleware(10_000), async (req, res) => { try { await deps.requireActor(req); const providerId = sanitizeText(req.params.providerId, 80); const [{ data: profile }, profileResult] = await Promise.all([supabaseAdmin.from("user_profiles").select("id,full_name,home_name,business_name").eq("id", providerId).maybeSingle(), supabaseAdmin.from("provider_payment_profiles").select("recipient_name,payment_type,phone_number,till_number,paybill_number,account_number,paypal_email,settlement_currency,is_active,is_verified").eq("provider_id", providerId).eq("is_active", true).maybeSingle()]); if (profileResult.error && profileResult.error.code !== "PGRST116") throw profileResult.error; const paymentProfile = profileResult.data || { recipient_name: profile?.home_name || profile?.business_name || profile?.full_name || "Provider", payment_type: "manual", phone_number: null, till_number: null, paybill_number: null, account_number: null, paypal_email: null, settlement_currency: "KES", is_active: true, is_verified: false }; res.json({ providerName: profile?.home_name || profile?.business_name || profile?.full_name || "Provider", paymentProfile }); } catch (error: any) { res.status(error.message?.includes("Authentication") ? 401 : 500).json({ error: error.message || "Could not load provider payment profile." }); } });

  app.post("/api/paypal/orders", deps.rateLimit("paypal-orders", 20), async (req, res) => { try { const actor = await deps.requireActor(req); const paypalClientId = getPaypalClientId(); const paypalSecret = getPaypalSecret(); if (!paypalClientId || !paypalSecret) return res.status(503).json({ error: "PayPal payments are temporarily unavailable. Please use mobile money payment instead.", code: "PAYPAL_NOT_CONFIGURED" }); const originalAmount = money(req.body?.originalAmount || req.body?.amount || req.body?.total || req.body?.value); const originalCurrency = normalizeCurrencyCode(req.body?.originalCurrency || req.body?.currency || "USD"); const settlementCurrency = paypalCurrency(req.body?.settlementCurrency || originalCurrency, "USD"); const settlementAmount = paypalSettlementAmount(originalAmount, originalCurrency, settlementCurrency); const description = sanitizeText(req.body?.description || req.body?.title || "Struta payment", 120); const providerPaypalEmail = sanitizeText(req.body?.providerPaypalEmail || req.body?.payeeEmail, 160); const payee = providerPaypalEmail ? { email_address: providerPaypalEmail } : undefined; const order = await paypalApi.createOrder({ intent: "CAPTURE", purchase_units: [{ reference_id: sanitizeText(req.body?.referenceId || req.body?.invoiceId || req.body?.requestId || actor.id, 120), description, custom_id: sanitizeText(req.body?.invoiceId || req.body?.requestId || "", 120), ...(payee ? { payee } : {}), amount: { currency_code: settlementCurrency, value: settlementAmount.toFixed(2) } }], application_context: { brand_name: "Struta", user_action: "PAY_NOW", shipping_preference: "NO_SHIPPING" } }); res.json({ id: order.id, order, amount: settlementAmount, currency: settlementCurrency, originalAmount, originalCurrency, fxRate: paypalFxRate(originalCurrency, settlementCurrency) }); } catch (error: any) { res.status(error.message?.includes("Authentication") ? 401 : 500).json({ error: error.message || "Could not create the PayPal order." }); } });
  app.post("/api/paypal/orders/:orderId/capture", deps.rateLimit("paypal-capture", 20), async (req, res) => { try { const actor = await deps.requireActor(req); const originalAmount = money(req.body?.originalAmount || req.body?.amount || 0); const originalCurrency = normalizeCurrencyCode(req.body?.originalCurrency || req.body?.currency || "USD"); const settlementCurrency = paypalCurrency(req.body?.settlementCurrency || originalCurrency, "USD"); const settlementAmount = paypalSettlementAmount(originalAmount, originalCurrency, settlementCurrency); const capture = await paypalApi.captureOrder(req.params.orderId); const captureItem = capture?.purchase_units?.[0]?.payments?.captures?.[0] || null; const captureId = captureItem?.id || null; const providerId = sanitizeText(req.body?.providerId, 80) || null; const providerType = sanitizeText(req.body?.providerType, 40) || null; const requestId = sanitizeText(req.body?.requestId, 80) || null; const invoiceId = sanitizeText(req.body?.invoiceId, 80) || null; const providerPaypalEmail = sanitizeText(req.body?.providerPaypalEmail || req.body?.payeeEmail, 160) || null; const payment = { user_id: actor.id, provider_id: providerId, provider_type: providerType, request_id: requestId, invoice_id: invoiceId, amount: originalAmount, amount_expected: originalAmount, amount_submitted: originalAmount, currency: originalCurrency, status: "paid", payment_method: "paypal", transaction_id: captureId || req.params.orderId, reference: captureId || req.params.orderId, submitted_at: new Date().toISOString(), confirmed_at: new Date().toISOString(), metadata: { capture, settlement_amount: settlementAmount, settlement_currency: settlementCurrency, original_amount: originalAmount, original_currency: originalCurrency, fx_rate: paypalFxRate(originalCurrency, settlementCurrency), provider_paypal_email: providerPaypalEmail } }; const { data, error } = await supabaseAdmin.from("payments").insert(payment).select("id").maybeSingle(); if (error) throw error; await recordInvoiceLedger({}); await syncPaidRequest(requestId, originalAmount, originalCurrency); clearApiCache(); publishRealtime({ type: "payment_paid", userId: actor.id, payload: { paymentId: data?.id, ...payment } }); if (providerId) await createRealtimeNotification(deps, { actorId: actor.id, userId: providerId, title: "Payment received", body: `${actor.email || "A family"} paid ${originalCurrency} ${originalAmount.toLocaleString()} by PayPal.`, type: "payment", deepLink: providerType === "vendor" ? "/marketplace/billing" : "/operations/billing" }); res.json({ ok: true, capture, captureId, paymentId: data?.id, settlementAmount, settlementCurrency, originalAmount, originalCurrency }); } catch (error: any) { res.status(error.message?.includes("Authentication") ? 401 : 500).json({ error: error.message || "Could not capture the PayPal order." }); } });
  app.post("/api/payment/stripe-intent", deps.rateLimit("stripe-intent", 20), async (_req, res) => { res.status(410).json({ error: "Stripe checkout has been disabled for invoice payments. Use PayPal or direct mobile money/manual payment." }); });
}
