FROM node:22-alpine AS builder
WORKDIR /app/frontend
COPY frontend/package.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/frontend/build ./build
COPY --from=builder /app/frontend/package.json ./package.json
EXPOSE 3000
CMD ["node", "build"]
