FROM golang:1.23-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /out/api ./cmd/api && go build -o /out/worker ./cmd/worker

FROM alpine:3.21
WORKDIR /app
RUN adduser -D learnzur
COPY --from=builder /out/api /app/api
COPY --from=builder /out/worker /app/worker
USER learnzur
EXPOSE 8080
CMD ["/app/api"]
