events {}
http { gzip on; server { listen 8088; add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always; location /api/auth/ { proxy_pass http://auth:8082/api/auth/; } location /api/ { proxy_pass http://api:8080/api/; } location / { proxy_pass http://frontend:3000/; } } }
