export const proPlanRewards = [
  {
    code: "milestone_unlocks",
    title: "Milestone Unlocks",
    description: "Vendors who complete 50 bookings unlock 2 weeks of Pro Plan.",
    reward: "14 Pro day(s)",
    rewardDays: 14,
    defaultEnabled: true,
  },
  {
    code: "streak_bonuses",
    title: "Streak Bonuses",
    description: "Maintain 30 days of active usage and earn 5 bonus days of Pro Plan.",
    reward: "5 Pro day(s)",
    rewardDays: 5,
    defaultEnabled: true,
  },
  {
    code: "leaderboard_incentives",
    title: "Leaderboard Incentives",
    description: "Top 5 vendors each month get Pro Plan extensions.",
    reward: "7 Pro day(s)",
    rewardDays: 7,
    defaultEnabled: true,
  },
  {
    code: "seasonal_challenges",
    title: "Seasonal Challenges",
    description: "During festive seasons, complete set goals such as 20 bookings to earn Pro Plan time.",
    reward: "7 Pro day(s)",
    rewardDays: 7,
    defaultEnabled: true,
  },
  {
    code: "vendor_growth_bonus",
    title: "Vendor Growth Bonus",
    description: "Vendors who onboard 5 new staff through the dashboard earn Pro Plan credits.",
    reward: "7 Pro day(s)",
    rewardDays: 7,
    defaultEnabled: true,
  },
  {
    code: "referral_rewards",
    title: "Referral Rewards",
    description: "Refer Struta to 10 families and earn 1 week of Pro Plan free.",
    reward: "7 Pro day(s)",
    rewardDays: 7,
    defaultEnabled: false,
  },
  {
    code: "family_loyalty",
    title: "Family Loyalty",
    description: "Families who use Struta for 3 or more events get a free Pro upgrade for their next booking.",
    reward: "7 Pro day(s)",
    rewardDays: 7,
    defaultEnabled: false,
  },
  {
    code: "feedback_rewards",
    title: "Feedback Rewards",
    description: "Submit verified feedback or feature requests and earn Pro Plan credits.",
    reward: "3 Pro day(s)",
    rewardDays: 3,
    defaultEnabled: false,
  },
  {
    code: "community_builder",
    title: "Community Builder",
    description: "Vendors who invite 3 other vendors to join Struta unlock Pro Plan days.",
    reward: "7 Pro day(s)",
    rewardDays: 7,
    defaultEnabled: false,
  },
] as const;
